# -*- mode: ruby -*-
Vagrant.configure('2') do |config|

  config.vm.box = "centos/7"
  config.vm.synced_folder "files/", "/vagrant"
  config.vm.network :public_network

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 4
  end

  # My access key
  config.vm.provision "shell", path: "./scripts/ssh-key.sh"

  # Global setup script
  config.vm.provision "shell", path: "./scripts/setup.sh"

  1.times do |i|
    node = "example#{i}"
    install_script = File.join("./scripts/","#{node}-setup.sh")
    config.vm.define node, autostart: false  do |v|
      v.vm.hostname = node
      v.vm.provision "shell", path: install_script if File.exist?(install_script)
    end
  end

end
