# -*- mode: ruby -*-
Vagrant.configure('2') do |config|

  config.vm.box = "centos/7"
  config.vm.synced_folder "files/", "/vagrant"
  config.vm.provision "shell", path: "./scripts/ssh-key.sh"
  config.vm.provision "shell", path: "./scripts/setup.sh"
  config.vm.network :public_network

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 4
  end

  config.vm.provision "shell", path: "./scripts/setup.sh"

  config.vm.define 'example1' do |v|
    v.vm.hostname = 'example1'
    install_script = File.join("./scripts/","#{v.vm.hostname}-setup.sh")
    v.vm.provision "shell", path: install_script if File.exist?(install_script)
  end

  config.vm.define 'example2', autostart: false  do |v|
    v.vm.hostname = 'example2'
    install_script = File.join("./scripts/","#{v.vm.hostname}-setup.sh")
    v.vm.provision "shell", path: install_script if File.exist?(install_script)
  end

end
