# -*- mode: ruby -*-
Vagrant.configure('2') do |config|

  config.vm.box = "centos/7"
  config.vm.synced_folder "files/", "/vagrant"
  config.vm.network :public_network

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 4
  end

  # My access key
  config.vm.provision "shell", path: "./scripts/ssh-key.sh"

  # Global setup script
  config.vm.provision "shell", path: "./scripts/global-setup.sh"

  [ "jenkins", "gitlab" ].each do |node|
    install_script = File.join("./scripts/","#{node}-setup.sh")
    config.vm.define node, autostart: false  do |v|
      v.vm.hostname = node
      v.vm.provision "shell", path: "./scripts/node-global-setup.sh"
      v.vm.provision "shell", path: install_script if File.exist?(install_script)
    end
  end

  config.vm.define :rebuildatron do |m|
    m.vm.hostname = "rebuildatron"

    m.vm.network "private_network", ip: "192.168.50.2"
    m.vm.provision "shell", path: "./scripts/rebuildatron-setup.sh"

    # Create a DVD drive per iso
    # Also move first boot device to disk so we don't boot from them
    m.vm.provider "virtualbox" do |vb|
      vb.customize [
        "modifyvm", :id,
        "--boot1","disk"
      ]
      port = 0
      Dir.glob('./*.iso').each do |iso|
	vb.customize [
	  "storageattach", :id, "--storagectl", "IDE",
	  "--port", port, "--device", "1",
	  "--type", "dvddrive",
	  "--medium", File.realpath(iso)
	]
	port += 1
      end
    end

  end

end
