---
- name: OpenVPN Server
  become: yes
  hosts: all
  tasks:

    - name: Install packages
      package:
        name:
          - openvpn
          - openssl
          - libpam-google-authenticator
          - fail2ban
        state: present

    - name: Ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present

    - name: Copy OpenVPN files and PKI
      copy:
        src: '{{item}}'
        dest: '/etc/openvpn/'
        owner: root
        group: root
        mode: 0640
      loop:
        - ../easy-rsa/pki/ca.crt
        - ../easy-rsa/pki/dh.pem
        - ../easy-rsa/pki/issued/openvpn-server.crt
        - ../easy-rsa/pki/private/openvpn-server.key
        - ../easy-rsa/pki/ta.key
        - ../etc/openvpn/server.conf
      notify:
        - Restart openvpn

    # Google Authenticator setup
    - name: google-auth dir
      file:
        path: /etc/google-auth
        state: directory
        owner: root
        group: root
        mode: '0740'
    - name: Openvpn pam for google auth
      copy:
        src: ../etc/pam.d/openvpn.pam
        dest: '/etc/pam.d/openvpn'
        owner: root
        group: root
        mode: 0640

    # Fail2Ban setup
    - name: Copy fail2ban configs
      copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: root
        group: root
        mode: 0640
      with_items:
        - {src: ../etc/fail2ban/filter.d/openvpn.conf,
           dest: /etc/fail2ban/filter.d/openvpn.conf}
        - {src: ../etc/fail2ban/jail.d/openvpn.conf,
           dest: /etc/fail2ban/jail.d/openvpn.conf}

    # Finally start all the services
    - name: enable openvpn, fail2ban
      service:
        name: '{{item}}'
        enabled: yes
        state: started
      loop:
        - openvpn@server
        - fail2ban

  handlers:
    - name: Restart openvpn
      service:
        name: openvpn@server
        state: restarted
    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted
