---
- name: OpenVPN Server
  become: yes
  hosts: all
  tasks:

    - name: Install packages
      package:
        name:
          - openvpn
          - openssl
          - libpam-google-authenticator
        state: present

    - name: Ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present

    - name: Copy OpenVPN files and PKI
      copy:
        src: '{{item}}'
        dest: '/etc/openvpn/'
        owner: root
        group: root
        mode: 0640
      loop:
        - ../easy-rsa/pki/ca.crt
        - ../easy-rsa/pki/dh.pem
        - ../easy-rsa/pki/issued/openvpn-server.crt
        - ../easy-rsa/pki/private/openvpn-server.key
        - ../easy-rsa/pki/ta.key
        - ../server.conf
      notify:
        - Restart openvpn

    # Google Authenticator setup
    - name: google-auth dir
      file:
        path: /etc/google-auth
        state: directory
        owner: root
        group: root
        mode: '0740'
    - name: Openvpn pam for google auth
      copy:
        src: ../openvpn.pam
        dest: '/etc/pam.d/openvpn'
        owner: root
        group: root
        mode: 0640

    # Finally start all the services
    - name: enable openvpn, fail2ban
      service:
        name: '{{item}}'
        enabled: yes
        state: started
      loop:
        - openvpn@server

  handlers:
    - name: Restart openvpn
      service:
        name: openvpn@server
        state: restarted
