---
- name: Webserver to prove we're on the VPN
  become: yes
  hosts: all
  tasks:
    - name: Installs the webserver
      package:
        name: apache2
        state: present

    - name: Enable
      service:
        name: apache2
        enabled: yes
        state: started
