# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.box = "centos/7"
  config.vm.network :public_network
  config.vm.synced_folder "files/", "/vagrant"
  config.vm.provision "shell", path: "./scripts/global-setup.sh"
  config.vm.provision "shell", path: "./scripts/ssh-key.sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 4
  end

  # Nodes
  config.vm.define 'node1' do |v|
    v.vm.hostname = 'node1'
    config.vm.provision "shell", path: "./scripts/node-setup.sh"
  end

  config.vm.define 'node2' do |v|
    v.vm.hostname = 'node2'
    config.vm.provision "shell", path: "./scripts/node-setup.sh"
  end

  # Servers
  config.vm.define 'puppet-master', autostart: false  do |v|
    v.vm.hostname = 'puppet-master'
    config.vm.provision "shell", path: "./scripts/puppet-master-setup.sh"
  end

end
