# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.box = "centos/7"
  config.vm.network :public_network
  config.vm.synced_folder "files/", "/vagrant"
  config.vm.provision "shell", path: "./scripts/global-setup.sh"
  config.vm.provision "shell", path: "./scripts/ssh-key.sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 4
  end

  # Nodes
  2.times do |node|
    config.vm.define "node#{node}" do |v|
      v.vm.hostname = "node#{node}"
      config.vm.provision "shell", path: "./scripts/node-setup.sh"
    end
  end

  # Servers
  config.vm.define 'puppet-master', autostart: false  do |v|
    v.vm.hostname = 'puppet-master'
    config.vm.provision "shell", path: "./scripts/puppet-master-setup.sh"
    v.vm.provider "virtualbox" do |v|
      v.memory = 3072
    end
  end

  config.vm.define 'salt-master', autostart: false  do |v|
    v.vm.hostname = 'salt-master'
    config.vm.provision "shell", path: "./scripts/salt-master-setup.sh"
    v.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
  end

end
